[package]
name = "secure_remove"
version = "2.1.0"
edition = "2021"

[[bin]]
name = "srm"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
